# Generated by Django 4.2 on 2023-05-04 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_applecation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choise',
            new_name='Choice',
        ),
    ]
